export {default as cpf} from './cep'
export {default as document} from './document'
export {default as grams} from './grams'
export {default as millimeters} from './millimeters'
export {default as percentage} from './percentage'
export {default as phone} from './phone'